  name: bump

  on:
    push:
      branches: [ main ]

  jobs:
    publish-client:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16
        - run: yarn
        - run: yarn build
        - run: npm publish
          working-directory: .
